env:
  global:
    - secure: fTLqnUG3vxsnZunscvRdV8aJ2+Byd5qEtfRXXGKmWgZYlPWQbWPpReIfbuPpUniLwWSNs9k8Casm1uKIsH5th5zWax7vvFCTQqRTUqrWvc6MPHjq02PjfgedtqfaZUFA4ms+bS0NNfUIgK9DkcIZb3vxgtPTI6sLStvHnIqrK5I=
install:
  - wget http://www.rust-lang.org/rustup.sh
  - sudo sh ./rustup.sh
  - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
  - rustc -v
script:
  - make
  - make test
  - make doctest
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
